### ISSUE TITLE
It is possible to allow multiple domains as options

### ISSUE THREAD

**Issue by robin-chilliapple** [helmetjs/frameguard#14]
Something like this:

app.use(helmet.frameguard({
	action: "allow-from",
	domain: ["https://example1.com", "https://example2.com", "https://example3.com"]
}));

**Comment by EvanHahn** [comment]
See [this part of the README](https://github.com/helmetjs/frameguard#allowing-from-multiple-origins).

**Comment by muhaimincs** [comment]
I miss it? Where is it?

**Comment by EvanHahn** [comment]
Because it's not natively supported by the `X-Frame-Options` header, this is something I'd discourage in favor of [Content-Security-Policy's `frame-ancestors` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors).
