### ISSUE TITLE
Documentation incorrect regaurding allow-from

### ISSUE THREAD

**Issue by FUberCab** [helmetjs/frameguard#21]
the documentation gives the following example

app.use(frameguard({
  action: 'allow-from',
  domain: 'https://example.com'
}))

while the package requires that the action me in all caps.

**Comment by EvanHahn** [comment]
Hmm, this snippet seems to work for me:

```js
frameguard({
  action: 'allow-from',
  domain: 'https://example.com'
})
```

Where does the package require that the action be in all caps?

**Comment by EvanHahn** [comment]
This issue has been open for a few months with no answer. Going to close this for now, but feel free to leave a comment and I'm happy to reopen.
