### ISSUE TITLE
Is there functionality to ignore a route?

### ISSUE THREAD

**Issue by ssolbak** [helmetjs/frameguard#5]
We have a single route that we want to be allowed to be framed. Is there a way to ignore by route rather than by host?

**Comment by EvanHahn** [comment]
Yes, but that would be at the Express layer.

To remove all of Frameguard from a route:

```js
app.get('/my-route-that-can-be-framed', function (req, res) {
  res.removeHeader('X-Frame-Options');
  // ...the rest of your handler...
});
```

To use a different Frameguard setup from a route:

```js
app.get('/my-route-that-can-be-framed', frameguard('sameorigin'), function (req, res) {
  // ...the rest of your handler...
});
```

Does that help?

**Comment by ssolbak** [comment]
Very much thanks!
