### ISSUE TITLE
Allow passing in options object

### ISSUE THREAD

**Issue by grtjn** [helmetjs/frameguard#7]
As in:

    app.use(frameguard({action: 'ALLOW-FROM', domains: ['foo', 'bar']});

Would make it easier to implement https://github.com/helmetjs/helmet/issues/112..

**Comment by grtjn** [comment]
Note: most if not all other helmetjs plugins seem to accept an options object, so would help consistency as well.

**Comment by grtjn** [comment]
A check to see if first arg is an object might allow backwards-compatibility..

**Comment by EvanHahn** [comment]
Completed this in 400df656289e8a257f8663332412e5de76360dae. Waiting for CI to tell me that it's okay to release, and then I'll release!

**Comment by EvanHahn** [comment]
I've released `frameguard@1.1.0` and a new release of `helmet` is soon to follow!
